config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show
  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Doc!

= render 'form'

= link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    -unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length:50)

    -else
      %h2 Create Doc!
      %p Start Creating Documents and Organizing your life!
      %button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 New Doc!

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc)
= link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?"}

app/views/layouts/_navgation.html.haml
-# .navbar.is-info
-#   .navbar-brand
-#     = link_to "FileCabinet", root_path, class: 'navbar-item'
-#   .navbar-menu
-#     .navbar-end
-#       - if user_signed_in?
-#         = link_to "Create Doc", new_doc_path, class: 'navbar-item'
-#         = link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-item'
-#
-#       -else
-#         = link_to "Log In", new_user_session_path, class: 'navbar-item'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FileCabinet | Your life's work!
    = stylesheet_link_tag   'application', media: 'all'
    = javascript_pack_tag 'application'
    = csrf_meta_tags
    = csp_meta_tag

  %body
    .navbar.is-info
      .navbar-brand
        = link_to "FileCabinet", root_path, class: 'navbar-item'
      .navbar-menu
        .navbar-end
          - if user_signed_in?
            = link_to "Create Doc", new_doc_path, class: 'navbar-item'
            = link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-item'

          -else
            = link_to "Log In", new_user_session_path, class: 'navbar-item'




    %p.notice= notice
    %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your lifes work. Organized, always.
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p I'm baby crucifix hashtag post-ironic sustainable chicharrones iceland
        hexagon chillwave narwhal tacos deep v copper mug letterpress 90's next level.
        Sriracha man bun lo-fi swag drinking vinegar, mustache pitchfork master cleanse kitsch.
        Cornhole humblebrag locavore deep v, hoodie small batch air plant la croix wayfarers
        franzen adaptogen. Post-ironic chia gluten-free bespoke fashion axe actually.
        Kogi post-ironic forage single-origin coffee.
#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to "Join Now", new_user_registration_path